version: "3"

services:

  db:
    image: postgres:10.1
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
  djangoapp:
    build: ./djangoapp
    ports:
      - "5000:5000"
    volumes:
      - ./djangoapp:/djangoapp
      - ./djangoapp/djangodrf/static:/static
      - ./djangoapp/djangodrf/media:/media

  flaskapp:
    build: ./flaskapp
    volumes:
      - .:/code
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development

volumes:
  postgresql-volume: # local to Linux, but in Windows it is not accessible
