version: "3"

services:

  db:
    image: postgres:10.1
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

  djangoapp:
    build: ./djangoapp
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./djangoapp:/djangoapp
      - ./djangoapp/djangodrf/static:/static
      - ./djangoapp/djangodrf/media:/media
    command: ./entrypoint.sh
    environment:
      - ALLOWED_HOSTS_PUSH=djangoapp

  flaskapp:
    build: ./flaskapp
    volumes:
      - ./flaskapp:/flaskapp
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
      - DRF_HOST=djangoapp
      - DRF_PORT=5000

volumes:
  postgresql-volume: # local to Linux, but in Windows it is not accessible
